document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '    <meta charset=\"UTF-8\">\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n' );
document.write( '    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n' );
document.write( '    <title>Document</title>\n' );
document.write( '    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '    <div class=\"tirecomparison-calculator\">\n' );
document.write( '        <div class=\"canvasHolder\">\n' );
document.write( '            <canvas class=\"canvas\" id=\"canvasA\"></canvas>\n' );
document.write( '            <canvas class=\"canvas\" id=\"canvasB\"></canvas>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"form_holder\">\n' );
document.write( '            <div class=\"form_one_container\">\n' );
document.write( '                <form class=\"form_one\">\n' );
document.write( '                    <div>\n' );
document.write( '                        <label for=\"tireWidth\">Outer Tire Width (mm)</label>\n' );
document.write( '                        <input id=\"tireWidth\" oninput=\"tireFunction()\" value=\"205\" type=\"number\" min=\"0\" max=\"399\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div>\n' );
document.write( '                        <label for=\"tireProfile\">Tire Profile</label>\n' );
document.write( '                        <input id=\"tireProfile\" oninput=\"tireFunction()\" value=\"55\" type=\"number\" min=\"0\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div>\n' );
document.write( '                        <label for=\"tireDiameter\">Tire Diameter (inches)</label>\n' );
document.write( '                        <input id=\"tireDiameter\" oninput=\"tireFunction()\" value=\"16\" type=\"number\" min=\"0\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '\n' );
document.write( '                    <div>\n' );
document.write( '                        <label for=\"offset\">Rim Offset (mm)</label>\n' );
document.write( '                        <input id=\"offset\" oninput=\"tireFunction()\" value=\"40\" type=\"number\" min=\"-99\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '\n' );
document.write( '                </form>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"form_two_container\">\n' );
document.write( '                <form class=\"form_two\">\n' );
document.write( '                    <div>\n' );
document.write( '                        <label for=\"twoTireWidth\">New Outer Tire Width (mm)</label>\n' );
document.write( '                        <input id=\"twoTireWidth\" oninput=\"twoTireFunction()\" value=\"235\" type=\"number\" min=\"0\" max=\"399\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div>\n' );
document.write( '                        <label for=\"twoTireProfile\">New Tire Profile</label>\n' );
document.write( '                        <input id=\"twoTireProfile\" oninput=\"twoTireFunction()\" value=\"40\" type=\"number\" min=\"0\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div>\n' );
document.write( '                        <label for=\"twoTireDiameter\">New Tire Diameter (inches)</label>\n' );
document.write( '                        <input id=\"twoTireDiameter\" oninput=\"twoTireFunction()\" value=\"17\" type=\"number\" min=\"0\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div>\n' );
document.write( '                        <label for=\"twoOffset\">New Rim Offset (mm)</label>\n' );
document.write( '                        <input id=\"twoOffset\" class=\"mm\" value=\"20\" oninput=\"twoTireFunction()\" type=\"number\" min=\"-99\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '                </form>\n' );
document.write( '            </div>\n' );
document.write( '        <br>\n' );
document.write( '        <div class=\"form-check\">\n' );
document.write( '            <input class=\"form-check-input\" onclick=\"checkTires()\" type=\"checkbox\" value=\"\" id=\"checkTires\" checked>\n' );
document.write( '            <label class=\"form-check-label\" for=\"checkTires\">\n' );
document.write( '                Show Tires\n' );
document.write( '            </label>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"form-check\">\n' );
document.write( '            <input class=\"form-check-input\" onclick=\"checkMeasurements()\" type=\"checkbox\" value=\"\" id=\"checkMeasurements\" checked>\n' );
document.write( '            <label class=\"form-check-label\" for=\"checkMeasurements\">\n' );
document.write( '                Show Measurements\n' );
document.write( '            </label>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"form-check advance_options\">\n' );
document.write( '            <input class=\"form-check-input\" onclick=\"checkClearance()\" type=\"checkbox\" value=\"\" id=\"checkClearance\">\n' );
document.write( '            <label class=\"form-check-label\" for=\"checkClearance\">\n' );
document.write( '                Show Clearance\n' );
document.write( '            </label>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"form-check advance_options\">\n' );
document.write( '            <input class=\"form-check-input\" onclick=\"checkFenderSuspension()\" type=\"checkbox\" value=\"\" id=\"checkFenderSuspension\">\n' );
document.write( '            <label class=\"form-check-label\" for=\"checkFenderSuspension\">\n' );
document.write( '                Show Fender and Suspension\n' );
document.write( '            </label>\n' );
document.write( '        </div>\n' );
document.write( '            <p></p>\n' );
document.write( '            <input type=\"button\" id=\"buttonToggle\" value=\"Show More Options\" onclick=\"toggleMode()\">\n' );
document.write( '            <div class=\"form_three_container\">\n' );
document.write( '                <form class=\"form_three\">\n' );
document.write( '                    <div class=\"block_one\">\n' );
document.write( '                        <div class=\"advance_options form_one\">\n' );
document.write( '                            <label for=\"width\">Inner Rim Width (mm)</label>\n' );
document.write( '                            <input id=\"width\" oninput=\"tireFunction()\" value=\"6.5\" type=\"number\" min=\"0\" max=\"99\">\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"advance_options form_one\">\n' );
document.write( '                            <label for=\"wheelwellWidth\">Wheelwell Clearance (mm) </label>\n' );
document.write( '                            <input id=\"wheelwellWidth\" oninput=\"tireFunction()\" value=\"0\" type=\"number\" min=\"-100\" max=\"100\">\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"advance_options form_one\">\n' );
document.write( '                            <label for=\"fenderWidth\">Fender Clearance (mm) </label>\n' );
document.write( '                            <input id=\"fenderWidth\" oninput=\"tireFunction()\" value=\"0\" type=\"number\" min=\"-100\" max=\"100\">\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"advance_options form_one\">\n' );
document.write( '                            <label for=\"suspensionWidth\">Suspension Width (mm)</label>\n' );
document.write( '                            <input id=\"suspensionWidth\" oninput=\"tireFunction()\" value=\"0\" type=\"number\" min=\"-100\" max=\"399\">\n' );
document.write( '                        </div>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"advance_options form_two\">\n' );
document.write( '                        <label for=\"twoWidth\">New Inner Rim Width (mm)</label>\n' );
document.write( '                        <input id=\"twoWidth\" class=\"ms\" value=\"6.5\" oninput=\"twoTireFunction()\" type=\"number\" min=\"-99\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"advance_options form_two\">\n' );
document.write( '                        <label for=\"twoWheelwellWidth\">New Wheelwell Clearance (mm) </label>\n' );
document.write( '                        <input id=\"twoWheelwellWidth\" oninput=\"twoTireFunction()\" value=\"0\" type=\"number\" min=\"-100\" max=\"100\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"advance_options form_two\">\n' );
document.write( '                        <label for=\"twoFenderWidth\">New Fender Clearance (mm)</label>\n' );
document.write( '                        <input id=\"twoFenderWidth\" oninput=\"twoTireFunction()\" value=\"0\" type=\"number\" min=\"-99\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"advance_options form_two\">\n' );
document.write( '                        <label for=\"twoSuspensionWidth\">New Suspension Width (mm)</label>\n' );
document.write( '                        <input id=\"twoSuspensionWidth\" oninput=\"twoTireFunction()\" value=\"0\" type=\"number\" min=\"0\" max=\"99\">\n' );
document.write( '                    </div>\n' );
document.write( '                </form>\n' );
document.write( '            </div>\n' );
document.write( '        <br>\n' );
document.write( '        <p>The strut shown in the diagram is for show only to help you visualize your tires.</p>\n' );
document.write( '        <p>Click on the \"Show\" button to display:</p>\n' );
document.write( '        <p>Inner Rims, Fender Clearance, Suspension Width, and Wheelwell Clearance</p>\n' );
document.write( '        <p>Tire Width    - The width of your tire in millimeters. <strong>195</strong>/55ZR15</p>\n' );
document.write( '        <p>Tire Profile  - The ratio of tire wall width to tire width. 195/<strong>55</strong>ZR15</p>\n' );
document.write( '        <p>Tire Diameter - The diameter of your wheels in inches. 195/55ZR<strong>15</strong> </p>\n' );
document.write( '        <div class=\"table-responsive\">\n' );
document.write( '            <table class=\"table table-sm\">\n' );
document.write( '                <colgroup>\n' );
document.write( '                    <col>\n' );
document.write( '                    <col>\n' );
document.write( '                    <col span=\"1\" class=\"bg-light\">\n' );
document.write( '                                   <col>\n' );
document.write( '                </colgroup>\n' );
document.write( '                <thead>\n' );
document.write( '                    <tr>\n' );
document.write( '                        <th id=\"measure\" scope=\"col\">Inches</th>\n' );
document.write( '                        <th scope=\"col\">Wheel 1</th>\n' );
document.write( '                        <th scope=\"col\">Wheel 2</th>\n' );
document.write( '                        <th scope=\"col\">Difference</th>\n' );
document.write( '                    </tr>\n' );
document.write( '                </thead>\n' );
document.write( '                <tbody>\n' );
document.write( '                    <tr>\n' );
document.write( '                        <th scope=\"row\">Diameter</th>\n' );
document.write( '                        <td id=\"diameterOne\"></td>\n' );
document.write( '                        <td id=\"diameterTwo\"></td>\n' );
document.write( '                        <td id=\"diameterPercentage\">%</td>\n' );
document.write( '                    </tr>\n' );
document.write( '                    <tr>\n' );
document.write( '                        <th scope=\"row\">Circumference</th>\n' );
document.write( '                        <td id=\"circumferenceOne\"></td>\n' );
document.write( '                        <td id=\"circumferenceTwo\"></td>\n' );
document.write( '                        <td id=\"circumferencePercentage\">%</td>\n' );
document.write( '                    </tr>\n' );
document.write( '                    <tr>\n' );
document.write( '                        <th scope=\"row\">Sidewall</th>\n' );
document.write( '                        <td id=\"sidewallOne\"></td>\n' );
document.write( '                        <td id=\"sidewallTwo\"></td>\n' );
document.write( '                        <td id=\"sidewallPercentage\">%</td>\n' );
document.write( '                    </tr>\n' );
document.write( '                    <tr>\n' );
document.write( '                        <th scope=\"row\">Width</th>\n' );
document.write( '                        <td id=\"widthOne\"></td>\n' );
document.write( '                        <td id=\"widthTwo\"></td>\n' );
document.write( '                        <td id=\"widthPercentage\">%</td>\n' );
document.write( '                    </tr>\n' );
document.write( '                    <tr>\n' );
document.write( '                        <th scope=\"row\">Wheel Revolutions</th>\n' );
document.write( '                        <td id=\"revOne\"></td>\n' );
document.write( '                        <td id=\"revTwo\"></td>\n' );
document.write( '                        <td id=\"revPercentage\"></td>\n' );
document.write( '                    </tr>\n' );
document.write( '                </tbody>\n' );
document.write( '            </table>\n' );
document.write( '        </div>\n' );
document.write( '    <br>\n' );
document.write( '        <input type=\"button\" id=\"buttonConvert\" value=\"Convert\" onclick=\"convertTable()\">\n' );
document.write( '    </div>\n' );
document.write( '</div>\n' );
document.write( '<style>\n' );
document.write( '    .form_holder{\n' );
document.write( '        background-color:#f8f8ff;\n' );
document.write( '        float: left;\n' );
document.write( '    }\n' );
document.write( '    .form_two{\n' );
document.write( '        color: blue;\n' );
document.write( '    }\n' );
document.write( '    .form_one_container{\n' );
document.write( '        float:left;\n' );
document.write( '    }\n' );
document.write( '    .block_one{\n' );
document.write( '        float:left;\n' );
document.write( '    }\n' );
document.write( '    .form_one{\n' );
document.write( '        margin-right: 20px;\n' );
document.write( '        color: red;\n' );
document.write( '    }\n' );
document.write( '    input, label {\n' );
document.write( '        display:block;\n' );
document.write( '    }\n' );
document.write( '    input[type=\"button\"] { \n' );
document.write( '        min-width: 32%;\n' );
document.write( '    }\n' );
document.write( '    input {\n' );
document.write( '        width: 70px;\n' );
document.write( '    }\n' );
document.write( '    .form-check-input {\n' );
document.write( '        width: 20px;\n' );
document.write( '    }\n' );
document.write( '    .canvasHolder{\n' );
document.write( '        float:left;\n' );
document.write( '        position: relative;\n' );
document.write( '        height: 500px; width: 320px; /*based on your canvas size*/\n' );
document.write( '    }\n' );
document.write( '    .canvas{\n' );
document.write( '        position: absolute;\n' );
document.write( '        top: 0; left: 0;\n' );
document.write( '        }\n' );
document.write( '    .tirecomparison-calculator {\n' );
document.write( '        background-color:#fcfcfc;\n' );
document.write( '        margin-left: auto;\n' );
document.write( '        margin-right: auto;\n' );
document.write( '        overflow: hidden;\n' );
document.write( '    }\n' );
document.write( '</style>\n' );
document.write( '<script>\n' );
document.write( '\n' );
document.write( 'let c = document.getElementById(\"canvasA\");\n' );
document.write( '    let d = document.getElementById(\"canvasB\");\n' );
document.write( '    let ctx = c.getContext(\"2d\");\n' );
document.write( '    let ctx2 = d.getContext(\"2d\");\n' );
document.write( '    let initialHeight = 500;\n' );
document.write( '    let initialWidth = 320;\n' );
document.write( '    c.width = initialWidth;\n' );
document.write( '    c.height = initialHeight;\n' );
document.write( '    d.width = initialWidth;\n' );
document.write( '    d.height = initialHeight;\n' );
document.write( '    let background = new Image();\n' );
document.write( '    background.src = \"https://sykjagni.sirv.com/jTkeSmK.gif\";\n' );
document.write( '\n' );
document.write( '    let tireImg = new Image();\n' );
document.write( '    tireImg.src = \"https://sykjagni.sirv.com/tire_PNG45.png\";\n' );
document.write( '\n' );
document.write( '    let inches = true;\n' );
document.write( '    let enabled = true;\n' );
document.write( '    let measure = true;\n' );
document.write( '    let tires = true;\n' );
document.write( '    let fendersuspension = false;\n' );
document.write( '    let clearance = false;\n' );
document.write( '    //if enabled disable the function to draw\n' );
document.write( '    function checkClearance(){\n' );
document.write( '        var remember = document.getElementById(\"checkClearance\");\n' );
document.write( '        if (remember.checked){\n' );
document.write( '            clearance = true;\n' );
document.write( '            tireFunction();\n' );
document.write( '            twoTireFunction();\n' );
document.write( '        }else{\n' );
document.write( '            clearance = false;\n' );
document.write( '            tireFunction();\n' );
document.write( '            twoTireFunction();\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '    function checkFenderSuspension(){\n' );
document.write( '        var remember = document.getElementById(\"checkFenderSuspension\");\n' );
document.write( '        if (remember.checked){\n' );
document.write( '            fendersuspension = true;\n' );
document.write( '            tireFunction();\n' );
document.write( '            twoTireFunction();\n' );
document.write( '        }else{\n' );
document.write( '            fendersuspension = false;\n' );
document.write( '            tireFunction();\n' );
document.write( '            twoTireFunction();\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    function checkMeasurements(){\n' );
document.write( '        var remember = document.getElementById(\"checkMeasurements\");\n' );
document.write( '        if (remember.checked){\n' );
document.write( '            measure = true;\n' );
document.write( '            tireFunction();\n' );
document.write( '            twoTireFunction();\n' );
document.write( '        }else{\n' );
document.write( '            measure = false;\n' );
document.write( '            tireFunction();\n' );
document.write( '            twoTireFunction();\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    function checkTires(){\n' );
document.write( '        var remembers = document.getElementById(\"checkTires\");\n' );
document.write( '        if (remembers.checked){\n' );
document.write( '            tires = true;\n' );
document.write( '            tireFunction();\n' );
document.write( '            twoTireFunction();\n' );
document.write( '        }else{\n' );
document.write( '            tires = false;\n' );
document.write( '            tireFunction();\n' );
document.write( '            twoTireFunction();\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    function toggleMode(){\n' );
document.write( '        var divsToHide = document.getElementsByClassName(\"advance_options\"); //divsToHide is an array\n' );
document.write( '        if (enabled === true){\n' );
document.write( '            enabled = false;\n' );
document.write( '            //hide elements\n' );
document.write( '            for(var i = 0; i < divsToHide.length; i++){\n' );
document.write( '                //divsToHide[i].style.visibility = \"hidden\"; // or\n' );
document.write( '                divsToHide[i].style.display = \"none\"; // depending on what you\"re doing\n' );
document.write( '            }\n' );
document.write( '            document.getElementById(\"buttonToggle\").value = \"Show More Options\";\n' );
document.write( '        }\n' );
document.write( '        else if (enabled === false) {\n' );
document.write( '            enabled = true;\n' );
document.write( '\n' );
document.write( '            for(var x = 0; x < divsToHide.length; x++){\n' );
document.write( '                //divsToHide[i].style.visibility = \"hidden\"; // or\n' );
document.write( '                divsToHide[x].style.display = \"block\"; // depending on what you\"re doing\n' );
document.write( '            }\n' );
document.write( '            document.getElementById(\"buttonToggle\").value = \"Hide\";\n' );
document.write( '\n' );
document.write( '        }\n' );
document.write( '        tireFunction();\n' );
document.write( '        twoTireFunction();\n' );
document.write( '    }\n' );
document.write( '    function processTableValues(colNum, tireHeight, tireSidewall, tiredWidth){\n' );
document.write( '        document.getElementById(\"diameter\" + colNum).textContent        = tireHeight.toFixed(2);\n' );
document.write( '        document.getElementById(\"circumference\" + colNum).textContent   = (3.14159 * tireHeight).toFixed(2);\n' );
document.write( '        document.getElementById(\"sidewall\" + colNum).textContent        = tireSidewall.toFixed(2);\n' );
document.write( '        document.getElementById(\"width\" + colNum).textContent           = (tiredWidth / 25.4).toFixed(2);\n' );
document.write( '        document.getElementById(\"rev\" + colNum).textContent             = (63360 / (3.14159 * tireHeight)).toFixed(0);\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    function processTableDifference(){\n' );
document.write( '        document.getElementById(\"diameterPercentage\").textContent       = ((((parseFloat(document.getElementById(\"diameterTwo\").textContent) - parseFloat(document.getElementById(\"diameterOne\").textContent)) / parseFloat(document.getElementById(\"diameterOne\").textContent) * 100)) || 0).toFixed(0) + \"%\";\n' );
document.write( '        document.getElementById(\"circumferencePercentage\").textContent  = (((parseFloat(document.getElementById(\"circumferenceTwo\").textContent) - parseFloat(document.getElementById(\"circumferenceOne\").textContent)) / parseFloat(document.getElementById(\"circumferenceOne\").textContent) * 100) || 0).toFixed(0) + \"%\";\n' );
document.write( '        document.getElementById(\"sidewallPercentage\").textContent       = (((parseFloat(document.getElementById(\"sidewallTwo\").textContent) - parseFloat(document.getElementById(\"sidewallOne\").textContent)) / parseFloat(document.getElementById(\"sidewallOne\").textContent) * 100) || 0).toFixed(0) + \"%\";\n' );
document.write( '        document.getElementById(\"widthPercentage\").textContent          = (((parseFloat(document.getElementById(\"widthTwo\").textContent) - parseFloat(document.getElementById(\"widthOne\").textContent)) / parseFloat(document.getElementById(\"widthOne\").textContent) * 100) || 0).toFixed(0) + \"%\";\n' );
document.write( '        document.getElementById(\"revPercentage\").textContent            = (parseFloat(document.getElementById(\"revTwo\").textContent) - parseFloat(document.getElementById(\"revOne\").textContent) || 0).toFixed(0);\n' );
document.write( '    }  \n' );
document.write( '\n' );
document.write( '    function convertTable() {\n' );
document.write( '        if (inches === true) {\n' );
document.write( '            document.getElementById(\"diameterOne\").textContent      = (parseFloat(document.getElementById(\"diameterOne\").textContent) * 25.4).toFixed(0);\n' );
document.write( '            document.getElementById(\"circumferenceOne\").textContent = (parseFloat(document.getElementById(\"circumferenceOne\").textContent) * 25.4).toFixed(0);\n' );
document.write( '            document.getElementById(\"sidewallOne\").textContent      = (parseFloat(document.getElementById(\"sidewallOne\").textContent) * 25.4).toFixed(0);\n' );
document.write( '            document.getElementById(\"widthOne\").textContent         = (parseFloat(document.getElementById(\"widthOne\").textContent) * 25.4).toFixed(0);\n' );
document.write( '\n' );
document.write( '            document.getElementById(\"diameterTwo\").textContent      = (parseFloat(document.getElementById(\"diameterTwo\").textContent) * 25.4).toFixed(0);\n' );
document.write( '            document.getElementById(\"circumferenceTwo\").textContent = (parseFloat(document.getElementById(\"circumferenceTwo\").textContent) * 25.4).toFixed(0);\n' );
document.write( '            document.getElementById(\"sidewallTwo\").textContent      = (parseFloat(document.getElementById(\"sidewallTwo\").textContent) * 25.4).toFixed(0);\n' );
document.write( '            document.getElementById(\"widthTwo\").textContent         = (parseFloat(document.getElementById(\"widthTwo\").textContent) * 25.4).toFixed(0);\n' );
document.write( '            document.getElementById(\"measure\").textContent          = \"Millimeters\";\n' );
document.write( '            inches = false;\n' );
document.write( '        } else if (inches === false) {\n' );
document.write( '            document.getElementById(\"diameterOne\").textContent      = (parseFloat(document.getElementById(\"diameterOne\").textContent) / 25.4).toFixed(2);\n' );
document.write( '            document.getElementById(\"circumferenceOne\").textContent = (parseFloat(document.getElementById(\"circumferenceOne\").textContent) / 25.4).toFixed(2);\n' );
document.write( '            document.getElementById(\"sidewallOne\").textContent      = (parseFloat(document.getElementById(\"sidewallOne\").textContent) / 25.4).toFixed(2);\n' );
document.write( '            document.getElementById(\"widthOne\").textContent         = (parseFloat(document.getElementById(\"widthOne\").textContent) / 25.4).toFixed(2);\n' );
document.write( '\n' );
document.write( '            document.getElementById(\"diameterTwo\").textContent      = (parseFloat(document.getElementById(\"diameterTwo\").textContent) / 25.4).toFixed(2);\n' );
document.write( '            document.getElementById(\"circumferenceTwo\").textContent = (parseFloat(document.getElementById(\"circumferenceTwo\").textContent) / 25.4).toFixed(2);\n' );
document.write( '            document.getElementById(\"sidewallTwo\").textContent      = (parseFloat(document.getElementById(\"sidewallTwo\").textContent) / 25.4).toFixed(2);\n' );
document.write( '            document.getElementById(\"widthTwo\").textContent         = (parseFloat(document.getElementById(\"widthTwo\").textContent) / 25.4).toFixed(2);\n' );
document.write( '            document.getElementById(\"measure\").textContent          = \"Inches\";\n' );
document.write( '            inches = true;\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '    \n' );
document.write( '    function drawDimensions(canvasNum, tireWidth1, tireWidth2, fenderWidth, midpoint1, midpoint2, tireProfile, tireHeight, tiredWidth, strokeColor, offset){\n' );
document.write( '        canvasNum.strokeStyle = strokeColor;\n' );
document.write( '\n' );
document.write( '        //x line\n' );
document.write( '        //big line\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo((tireWidth1) - fenderWidth - 50, midpoint1 - tireProfile); //top\n' );
document.write( '        canvasNum.lineTo((tireWidth1) - fenderWidth - 50, midpoint2 + tireProfile); //bottom\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '        //x text\n' );
document.write( '        canvasNum.font = \"15px Helvetica\";\n' );
document.write( '        canvasNum.fillStyle = strokeColor;\n' );
document.write( '        canvasNum.fillText(tireHeight.toFixed(1),  (tireWidth1) - fenderWidth - 80, ((midpoint1 - tireProfile) + (midpoint2 + tireProfile)) / 2 + offset);\n' );
document.write( '\n' );
document.write( '        //top line\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo((tireWidth1) - fenderWidth - 50, midpoint1 - tireProfile);\n' );
document.write( '        canvasNum.lineTo((tireWidth1) - fenderWidth - 20, midpoint1 - tireProfile);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '\n' );
document.write( '        //bottom line\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo((tireWidth1) - fenderWidth - 20, midpoint2 + tireProfile);\n' );
document.write( '        canvasNum.lineTo((tireWidth1) - fenderWidth - 50, midpoint2 + tireProfile);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '\n' );
document.write( '        //y line\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth1, (midpoint1 - tireProfile) - 30);\n' );
document.write( '        canvasNum.lineTo(tireWidth2, (midpoint1 - tireProfile) - 30);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '        //y text\n' );
document.write( '        canvasNum.textBaseline = \"bottom\";\n' );
document.write( '        canvasNum.fillText((tiredWidth / 25.4).toFixed(2),  (tireWidth1 + tireWidth2) / 2 - 20 + offset , (midpoint1 - tireProfile) - 30);\n' );
document.write( '\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth1, (midpoint1 - tireProfile) - 30);\n' );
document.write( '        canvasNum.lineTo(tireWidth1, (midpoint1 - tireProfile) - 10);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth2, (midpoint1 - tireProfile) - 30);\n' );
document.write( '        canvasNum.lineTo(tireWidth2, (midpoint1 - tireProfile) - 10);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '        \n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    function drawFenderSuspension(canvasNum, newWidth, tireWidth1, tireWidth2, midpoint1, midpoint2, tireProfile, fenderWidth, suspensionWidth, strokeColor){\n' );
document.write( '        //draw fender line\n' );
document.write( '        if (enabled === true && measure === true){\n' );
document.write( '            if (tireWidth1 > newWidth){ \n' );
document.write( '            canvasNum.beginPath();\n' );
document.write( '            canvasNum.setLineDash([2,3]);\n' );
document.write( '            canvasNum.strokeStyle = strokeColor;\n' );
document.write( '            canvasNum.moveTo((newWidth) - fenderWidth, midpoint1 - tireProfile);\n' );
document.write( '            canvasNum.lineTo((newWidth) - fenderWidth, midpoint2 + tireProfile);\n' );
document.write( '            canvasNum.stroke();\n' );
document.write( '            canvasNum.setLineDash([]);\n' );
document.write( '            }\n' );
document.write( '            else {\n' );
document.write( '            canvasNum.beginPath();\n' );
document.write( '            canvasNum.strokeStyle = strokeColor;\n' );
document.write( '            canvasNum.setLineDash([2,3]);\n' );
document.write( '\n' );
document.write( '            canvasNum.moveTo((tireWidth1) - fenderWidth, midpoint1 - tireProfile);\n' );
document.write( '            canvasNum.lineTo((tireWidth1) - fenderWidth, midpoint2 + tireProfile);\n' );
document.write( '            canvasNum.stroke();\n' );
document.write( '            canvasNum.setLineDash([]);\n' );
document.write( '            }\n' );
document.write( '            //draw suspension line\n' );
document.write( '            canvasNum.beginPath();\n' );
document.write( '            canvasNum.strokeStyle = strokeColor;\n' );
document.write( '            canvasNum.setLineDash([2,3]);\n' );
document.write( '            canvasNum.moveTo(tireWidth2 + (suspensionWidth), midpoint1 - tireProfile);\n' );
document.write( '            canvasNum.lineTo(tireWidth2 + (suspensionWidth), midpoint2 + tireProfile);\n' );
document.write( '            canvasNum.stroke();\n' );
document.write( '            canvasNum.setLineDash([]);\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    function drawClearance(canvasNum, wheelwellWidth, midpoint1, midpoint2, tireProfile, strokeColor){\n' );
document.write( '        if (enabled === true && measure === true){\n' );
document.write( '\n' );
document.write( '        //draw fender line\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.strokeStyle = strokeColor;\n' );
document.write( '        canvasNum.moveTo(50,  (midpoint1 - tireProfile) - wheelwellWidth/2);\n' );
document.write( '        canvasNum.lineTo(250, (midpoint1 - tireProfile) - wheelwellWidth/2);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '    function drawProfile(canvasNum, tireWidth1, tireWidth2, widthValue, midpoint1, midpoint2, tireProfile, offsetValue){\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth1, midpoint1 - tireProfile);\n' );
document.write( '        canvasNum.lineTo(offsetValue, midpoint1);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '        \n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth2, midpoint1 - tireProfile);\n' );
document.write( '        canvasNum.lineTo(offsetValue + widthValue, midpoint1);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '        \n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth1, midpoint2 + tireProfile);\n' );
document.write( '        canvasNum.lineTo(offsetValue, midpoint2);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '        \n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth2, midpoint2 + tireProfile);\n' );
document.write( '        canvasNum.lineTo(offsetValue + widthValue, midpoint2);\n' );
document.write( '        canvasNum.stroke();        \n' );
document.write( '    }\n' );
document.write( '    function drawWidth(canvasNum, tireWidth1, tireWidth2, midpoint1, midpoint2, tireProfile){\n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth1, (midpoint1 - tireProfile)); //midpoint of rectangle\n' );
document.write( '        canvasNum.lineTo(tireWidth2, (midpoint1 - tireProfile));\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '        \n' );
document.write( '        canvasNum.beginPath();\n' );
document.write( '        canvasNum.moveTo(tireWidth1, midpoint2 + tireProfile); //midpoint of rectangle\n' );
document.write( '        canvasNum.lineTo(tireWidth2, midpoint2 + tireProfile);\n' );
document.write( '        canvasNum.stroke();\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    function tireFunction() { //first set\n' );
document.write( '        ctx.clearRect(0, 0, 320, 500);\n' );
document.write( '        ctx.drawImage(background, 0, 0);\n' );
document.write( '        let width           = document.getElementById(\"width\").value * 12;\n' );
document.write( '        let offset          = document.getElementById(\"offset\").value / 2;\n' );
document.write( '        let tireWidth       = parseInt(document.getElementById(\"tireWidth\").value) / 4;\n' );
document.write( '        let tireProfile     = parseInt(document.getElementById(\"tireProfile\").value) * 1.1;\n' );
document.write( '        let tireDiameter    = parseInt(document.getElementById(\"tireDiameter\").value) * 12.5;\n' );
document.write( '        let fenderWidth     = parseInt(document.getElementById(\"fenderWidth\").value) || 0;\n' );
document.write( '        let suspensionWidth = parseInt(document.getElementById(\"suspensionWidth\").value) || 0;\n' );
document.write( '        let wheelwellWidth  = parseInt(document.getElementById(\"wheelwellWidth\").value) || 0;\n' );
document.write( '\n' );
document.write( '        let tiredWidth      = parseInt(document.getElementById(\"tireWidth\").value);\n' );
document.write( '        let tiredProfile    = parseInt(document.getElementById(\"tireProfile\").value);\n' );
document.write( '        let tiredDiameter   = parseInt(document.getElementById(\"tireDiameter\").value);\n' );
document.write( '        let tireSidewall    = (tiredWidth * (tiredProfile / 100)) / 25.4;\n' );
document.write( '        let tireHeight      = ((((tiredWidth * (tiredProfile / 100)) * 2) + (tiredDiameter * 25.4)) / 25.4);\n' );
document.write( '\n' );
document.write( '        processTableValues(\"One\", tireHeight, tireSidewall, tiredWidth);\n' );
document.write( '        processTableDifference();\n' );
document.write( '\n' );
document.write( '        let widthValue = 15 + parseInt(width);\n' );
document.write( '        let offsetValue = 140 + parseInt(offset) - parseInt(width) / 2;\n' );
document.write( '        let midpoint1 = (440 - tireDiameter) / 2;\n' );
document.write( '        let midpoint2 = (440 + tireDiameter) / 2;\n' );
document.write( '\n' );
document.write( '        tireProfile = ((tireHeight * 12.25) - (midpoint2 - midpoint1)) / 2;\n' );
document.write( '\n' );
document.write( '        let tireWidth2 = offsetValue + tireWidth + (widthValue / 2);\n' );
document.write( '        let tireWidth1 = offsetValue - tireWidth + (widthValue / 2);\n' );
document.write( '\n' );
document.write( '        if (measure === true){\n' );
document.write( '            drawDimensions(ctx, tireWidth1, tireWidth2, fenderWidth, midpoint1, midpoint2, tireProfile, tireHeight, tiredWidth, \"#FF0000\", 0);\n' );
document.write( '\n' );
document.write( '            //draw rect\n' );
document.write( '            ctx.beginPath();\n' );
document.write( '            ctx.strokeStyle    = \"#FF0000\";\n' );
document.write( '            ctx.lineWidth      = 1.5;\n' );
document.write( '            if (tires === true){\n' );
document.write( '                ctx.rect(147.5 + parseInt(offset) - ((tireWidth2 - tireWidth1) /2) , ((440 - tireDiameter) / 2) - tireProfile, tireWidth2 - tireWidth1, tireDiameter + (tireProfile * 2)); //x,y,width,height\n' );
document.write( '                ctx.drawImage(tireImg,  147.5 + parseInt(offset) - ((tireWidth2 - tireWidth1) /2) , ((440 - tireDiameter) / 2) - tireProfile, tireWidth2 - tireWidth1, tireDiameter + (tireProfile * 2)); //x,y,width,height\n' );
document.write( '            }\n' );
document.write( '            if (enabled === false){\n' );
document.write( '            ctx.rect(147.5 + parseInt(offset) - ((tireWidth2 - tireWidth1) /2) , ((440 - tireDiameter) / 2) - tireProfile, tireWidth2 - tireWidth1, tireDiameter + (tireProfile * 2)); //x,y,width,height\n' );
document.write( '            }\n' );
document.write( '            else{\n' );
document.write( '            ctx.rect(offsetValue, (440 - tireDiameter) / 2, widthValue, tireDiameter); //x,y,width,height\n' );
document.write( '            }\n' );
document.write( '            ctx.stroke();\n' );
document.write( '            ctx.strokeStyle = \"#000000\";\n' );
document.write( '            if (enabled === true){\n' );
document.write( '\n' );
document.write( '            //draw lines on top and below the rectangle\n' );
document.write( '            drawWidth(ctx, tireWidth1, tireWidth2, midpoint1, midpoint2, tireProfile);\n' );
document.write( '\n' );
document.write( '            //draw two lines connecting the tire widths to the base of the rectangle\n' );
document.write( '            drawProfile(ctx, tireWidth1, tireWidth2, widthValue, midpoint1, midpoint2, tireProfile, offsetValue);\n' );
document.write( '            ctx.strokeStyle = \"#FF0000\";\n' );
document.write( '\n' );
document.write( '            //draw fender and suspension lines\n' );
document.write( '            if (fendersuspension === true){\n' );
document.write( '                drawFenderSuspension(ctx, offsetValue, tireWidth1, tireWidth2, midpoint1, midpoint2, tireProfile, fenderWidth, suspensionWidth, \"#FF0000\");\n' );
document.write( '            }\n' );
document.write( '\n' );
document.write( '            if (clearance === true){\n' );
document.write( '            drawClearance(ctx, wheelwellWidth ,midpoint1, midpoint2, tireProfile, \"#FF0000\");\n' );
document.write( '            }\n' );
document.write( '            }\n' );
document.write( '        }\n' );
document.write( '\n' );
document.write( '        else if (measure === false){\n' );
document.write( '            ctx.beginPath();\n' );
document.write( '            ctx.strokeStyle    = \"#FF0000\";\n' );
document.write( '            ctx.lineWidth      = 1.5;\n' );
document.write( '            ctx.drawImage(tireImg,  147.5 + parseInt(offset) - ((tireWidth2 - tireWidth1) /2) , ((440 - tireDiameter) / 2) - tireProfile, tireWidth2 - tireWidth1, tireDiameter + (tireProfile * 2)); //x,y,width,height\n' );
document.write( '            ctx.stroke();\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    function twoTireFunction() {\n' );
document.write( '        ctx2.clearRect(0, 0, 320, 500);\n' );
document.write( '\n' );
document.write( '        let width           = (document.getElementById(\"twoWidth\").value) * 12;\n' );
document.write( '        let offset          = (document.getElementById(\"twoOffset\").value) / 2;\n' );
document.write( '        let tireWidth       = (parseInt(document.getElementById(\"twoTireWidth\").value)) / 4;\n' );
document.write( '        let tireProfile     = (parseInt(document.getElementById(\"twoTireProfile\").value)) * 1.1;\n' );
document.write( '        let tireDiameter    = (parseInt(document.getElementById(\"twoTireDiameter\").value)) * 12.5;\n' );
document.write( '\n' );
document.write( '        let tiredWidth      = parseInt(document.getElementById(\"twoTireWidth\").value);\n' );
document.write( '        let tiredProfile    = parseInt(document.getElementById(\"twoTireProfile\").value);\n' );
document.write( '        let tiredDiameter   = parseInt(document.getElementById(\"twoTireDiameter\").value);\n' );
document.write( '        let fenderWidth     = (parseInt(document.getElementById(\"twoFenderWidth\").value)) || 0;\n' );
document.write( '        let suspensionWidth = parseInt(document.getElementById(\"twoSuspensionWidth\").value) || 0;\n' );
document.write( '        let wheelwellWidth  = parseInt(document.getElementById(\"twoWheelwellWidth\").value) || 0;\n' );
document.write( '\n' );
document.write( '        let tireSidewall    = (tiredWidth * (tiredProfile / 100)) / 25.4;\n' );
document.write( '        let tireHeight      = (((tiredWidth * (tiredProfile / 100))  * 2) + (tiredDiameter * 25.4)) / 25.4;\n' );
document.write( '\n' );
document.write( '        processTableValues(\"Two\", tireHeight, tireSidewall, tiredWidth);\n' );
document.write( '        processTableDifference();\n' );
document.write( '\n' );
document.write( '        let widthValue  = 15 + parseInt(width);\n' );
document.write( '        let offsetValue = 140 + parseInt(offset) - parseInt(width) / 2;\n' );
document.write( '        let midpoint1   = (440 - tireDiameter) / 2;\n' );
document.write( '        let midpoint2   = (440 + tireDiameter) / 2;\n' );
document.write( '\n' );
document.write( '        tireProfile     = ((tireHeight * 12.25) - (midpoint2 - midpoint1)) / 2;\n' );
document.write( '\n' );
document.write( '        let tireWidth2  = offsetValue + tireWidth + (widthValue / 2);\n' );
document.write( '        let tireWidth1  = offsetValue - tireWidth + (widthValue / 2);\n' );
document.write( '\n' );
document.write( '        if (measure === true){\n' );
document.write( '            drawDimensions(ctx2, tireWidth1, tireWidth2, fenderWidth, midpoint1, midpoint2, tireProfile, tireHeight, tiredWidth, \"#0000FF\", 50);\n' );
document.write( '\n' );
document.write( '            //draw rect\n' );
document.write( '            ctx2.beginPath();\n' );
document.write( '            ctx2.strokeStyle    = \"#0000FF\";\n' );
document.write( '            ctx2.lineWidth      = 1.5;\n' );
document.write( '            if (enabled === false){\n' );
document.write( '            ctx2.rect(147.5 + parseInt(offset) - ((tireWidth2 - tireWidth1) /2) , ((440 - tireDiameter) / 2) - tireProfile, tireWidth2 - tireWidth1, tireDiameter + (tireProfile * 2)); //x,y,width,height\n' );
document.write( '            }\n' );
document.write( '            else {\n' );
document.write( '            ctx2.rect(offsetValue, (440 - tireDiameter) / 2, widthValue, tireDiameter); //x,y,width,height\n' );
document.write( '            }\n' );
document.write( '            if (tires === true){\n' );
document.write( '            ctx2.rect(147.5 + parseInt(offset) - ((tireWidth2 - tireWidth1) /2) , ((440 - tireDiameter) / 2) - tireProfile, tireWidth2 - tireWidth1, tireDiameter + (tireProfile * 2)); //x,y,width,height\n' );
document.write( '            ctx2.globalAlpha    = 0.35;\n' );
document.write( '            ctx2.drawImage(tireImg,  147.5 + parseInt(offset) - ((tireWidth2 - tireWidth1) /2) , ((440 - tireDiameter) / 2) - tireProfile, tireWidth2 - tireWidth1, tireDiameter + (tireProfile * 2)); //x,y,width,height\n' );
document.write( '            ctx2.globalAlpha    = 1;\n' );
document.write( '            }\n' );
document.write( '            ctx2.stroke();\n' );
document.write( '            ctx2.strokeStyle = \"#000000\";\n' );
document.write( '            if (enabled === true){\n' );
document.write( '\n' );
document.write( '                //draw lines on top and below the rectangle\n' );
document.write( '                drawWidth(ctx2, tireWidth1, tireWidth2, midpoint1, midpoint2, tireProfile);\n' );
document.write( '\n' );
document.write( '                //draw two lines connecting the tire widths to the base of the rectangle\n' );
document.write( '                drawProfile(ctx2, tireWidth1, tireWidth2, widthValue, midpoint1, midpoint2, tireProfile, offsetValue);\n' );
document.write( '                ctx2.strokeStyle = \"#0000FF\";\n' );
document.write( '\n' );
document.write( '                //draw fender and suspension lines\n' );
document.write( '                if (fendersuspension === true){\n' );
document.write( '                drawFenderSuspension(ctx2, offsetValue, tireWidth1, tireWidth2, midpoint1, midpoint2, tireProfile, fenderWidth, suspensionWidth, \"#0000FF\");\n' );
document.write( '                }\n' );
document.write( '\n' );
document.write( '                if (clearance === true){\n' );
document.write( '                    drawClearance(ctx2, wheelwellWidth ,midpoint1, midpoint2, tireProfile, \"#0000FF\");\n' );
document.write( '                }\n' );
document.write( '            }\n' );
document.write( '        }\n' );
document.write( '\n' );
document.write( '        else if (measure === false){\n' );
document.write( '            ctx2.beginPath();\n' );
document.write( '            ctx2.strokeStyle    = \"#0000FF\";\n' );
document.write( '            ctx2.lineWidth      = 1.5;\n' );
document.write( '            ctx2.globalAlpha    = 0.35;\n' );
document.write( '\n' );
document.write( '            ctx2.drawImage(tireImg,  147.5 + parseInt(offset) - ((tireWidth2 - tireWidth1) /2) , ((440 - tireDiameter) / 2) - tireProfile, tireWidth2 - tireWidth1, tireDiameter + (tireProfile * 2)); //x,y,width,height\n' );
document.write( '            ctx2.globalAlpha    = 1;\n' );
document.write( '\n' );
document.write( '            ctx2.stroke();\n' );
document.write( '        }\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    }\n' );
document.write( '    // Make sure the image is loaded first otherwise nothing will draw.\n' );
document.write( '\n' );
document.write( '    background.onload = function () {\n' );
document.write( '        toggleMode();\n' );
document.write( '        ctx.drawImage(tireImg,0 ,0 ,0, 0);\n' );
document.write( '        ctx2.drawImage(tireImg, 0, 0, 0, 0);\n' );
document.write( '        \n' );
document.write( '        var allowedDomains = [\'127.0.0.1\', \'example2.com\'];\n' );
document.write( '        console.log(document.domain);\n' );
document.write( '        if (allowedDomains.indexOf(document.domain) == -1) {\n' );
document.write( '        // Code to redirect here\n' );
document.write( '        console.log(\'wrong domain\');\n' );
document.write( '        }\n' );
document.write( '        else{\n' );
document.write( '            console.log(\'correct\');\n' );
document.write( '        }\n' );
document.write( '    };\n' );
document.write( '</script>\n' );
document.write( '</body>\n' );
document.write( '</html>' );